"""Agregar campo rol a Dueño

Revision ID: 0f28bc1b8eb2
Revises: 4c2f1662ac67
Create Date: 2025-02-18 12:46:36.989788

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f28bc1b8eb2'
down_revision = '4c2f1662ac67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dueños', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rol', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dueños', schema=None) as batch_op:
        batch_op.drop_column('rol')

    # ### end Alembic commands ###
