"""Add password_hash column to dueños

Revision ID: 4c2f1662ac67
Revises: ea4832e64853
Create Date: 2025-02-17 19:12:58.170104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c2f1662ac67'
down_revision = 'ea4832e64853'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dueños', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dueños', schema=None) as batch_op:
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###
