"""Add cedula column to Dueño model

Revision ID: ea4832e64853
Revises: 
Create Date: 2025-02-17 02:33:11.743531

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea4832e64853'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dueños', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cedula', sa.String(length=20), nullable=False))
        # Ahora pasamos solo la columna en la lista
        batch_op.create_unique_constraint('uq_dueños_cedula', ['cedula'])

    with op.batch_alter_table('mascotas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dueño_id', sa.Integer(), nullable=True))
        # Agregar la clave foránea
        batch_op.create_foreign_key('fk_mascotas_dueño_id', 'dueños', ['dueño_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mascotas', schema=None) as batch_op:
        batch_op.drop_constraint('fk_mascotas_dueño_id', type_='foreignkey')
        batch_op.drop_column('dueño_id')

    with op.batch_alter_table('dueños', schema=None) as batch_op:
        batch_op.drop_constraint('uq_dueños_cedula', type_='unique')
        batch_op.drop_column('cedula')

    # ### end Alembic commands ###
